name: sarah-scherer
favicon: null
layout_spectrum: 0.12818937143310905
typography_spectrum: 0.34274924313649535
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f9f9f9'
    - '#c0bfba'
    - '#9b9691'
    - '#534e48'
  brandStrength: 0.6901229450013489
  lightness: 0.7641203342936933
  saturation: 0.1721321891527623
  rhythmicContrast: 0.5183288299012929
purpose: []
